// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/ipc/message/protobuf/hdmap/enginesurmap.proto

#ifndef PROTOBUF_modules_2fipc_2fmessage_2fprotobuf_2fhdmap_2fenginesurmap_2eproto__INCLUDED
#define PROTOBUF_modules_2fipc_2fmessage_2fprotobuf_2fhdmap_2fenginesurmap_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include "modules/ipc/message/protobuf/common/header.pb.h"
#include "modules/ipc/message/protobuf/common/reserved.pb.h"
#include "modules/ipc/message/protobuf/localization/pose.pb.h"
#include "modules/ipc/message/protobuf/common/geometry.pb.h"
#include "modules/ipc/message/protobuf/hdmap/engineremaindistance.pb.h"
// @@protoc_insertion_point(includes)
namespace atd {
namespace common {
class Arrow2D;
class Arrow2DDefaultTypeInternal;
extern Arrow2DDefaultTypeInternal _Arrow2D_default_instance_;
class Header;
class HeaderDefaultTypeInternal;
extern HeaderDefaultTypeInternal _Header_default_instance_;
class Point2D;
class Point2DDefaultTypeInternal;
extern Point2DDefaultTypeInternal _Point2D_default_instance_;
class Point3D;
class Point3DDefaultTypeInternal;
extern Point3DDefaultTypeInternal _Point3D_default_instance_;
class PointENU;
class PointENUDefaultTypeInternal;
extern PointENUDefaultTypeInternal _PointENU_default_instance_;
class PointLLH;
class PointLLHDefaultTypeInternal;
extern PointLLHDefaultTypeInternal _PointLLH_default_instance_;
class Quaternion;
class QuaternionDefaultTypeInternal;
extern QuaternionDefaultTypeInternal _Quaternion_default_instance_;
class Reserved;
class ReservedDefaultTypeInternal;
extern ReservedDefaultTypeInternal _Reserved_default_instance_;
}  // namespace common
namespace localization {
class Pose;
class PoseDefaultTypeInternal;
extern PoseDefaultTypeInternal _Pose_default_instance_;
}  // namespace localization
namespace map {
class EngineRemainDistance;
class EngineRemainDistanceDefaultTypeInternal;
extern EngineRemainDistanceDefaultTypeInternal _EngineRemainDistance_default_instance_;
class EngineSurMap;
class EngineSurMapDefaultTypeInternal;
extern EngineSurMapDefaultTypeInternal _EngineSurMap_default_instance_;
class LANE_LINK_KEY;
class LANE_LINK_KEYDefaultTypeInternal;
extern LANE_LINK_KEYDefaultTypeInternal _LANE_LINK_KEY_default_instance_;
class ONE_PARKING_SITE;
class ONE_PARKING_SITEDefaultTypeInternal;
extern ONE_PARKING_SITEDefaultTypeInternal _ONE_PARKING_SITE_default_instance_;
class SPEED_LIMIT;
class SPEED_LIMITDefaultTypeInternal;
extern SPEED_LIMITDefaultTypeInternal _SPEED_LIMIT_default_instance_;
class SurElement;
class SurElementDefaultTypeInternal;
extern SurElementDefaultTypeInternal _SurElement_default_instance_;
class SurElements;
class SurElementsDefaultTypeInternal;
extern SurElementsDefaultTypeInternal _SurElements_default_instance_;
class TSR_DISTANCE;
class TSR_DISTANCEDefaultTypeInternal;
extern TSR_DISTANCEDefaultTypeInternal _TSR_DISTANCE_default_instance_;
}  // namespace map
}  // namespace atd

namespace atd {
namespace map {

namespace protobuf_modules_2fipc_2fmessage_2fprotobuf_2fhdmap_2fenginesurmap_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_modules_2fipc_2fmessage_2fprotobuf_2fhdmap_2fenginesurmap_2eproto

// ===================================================================

class SurElement : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:atd.map.SurElement) */ {
 public:
  SurElement();
  virtual ~SurElement();

  SurElement(const SurElement& from);

  inline SurElement& operator=(const SurElement& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const SurElement& default_instance();

  static inline const SurElement* internal_default_instance() {
    return reinterpret_cast<const SurElement*>(
               &_SurElement_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(SurElement* other);

  // implements Message ----------------------------------------------

  inline SurElement* New() const PROTOBUF_FINAL { return New(NULL); }

  SurElement* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    PROTOBUF_FINAL;
  void CopyFrom(const SurElement& from);
  void MergeFrom(const SurElement& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  void DiscardUnknownFields();
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SurElement* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .atd.common.Point2D onepoint = 3;
  int onepoint_size() const;
  void clear_onepoint();
  static const int kOnepointFieldNumber = 3;
  const ::atd::common::Point2D& onepoint(int index) const;
  ::atd::common::Point2D* mutable_onepoint(int index);
  ::atd::common::Point2D* add_onepoint();
  ::google::protobuf::RepeatedPtrField< ::atd::common::Point2D >*
      mutable_onepoint();
  const ::google::protobuf::RepeatedPtrField< ::atd::common::Point2D >&
      onepoint() const;

  // optional int32 majortype = 1;
  bool has_majortype() const;
  void clear_majortype();
  static const int kMajortypeFieldNumber = 1;
  ::google::protobuf::int32 majortype() const;
  void set_majortype(::google::protobuf::int32 value);

  // optional int32 minortype = 2;
  bool has_minortype() const;
  void clear_minortype();
  static const int kMinortypeFieldNumber = 2;
  ::google::protobuf::int32 minortype() const;
  void set_minortype(::google::protobuf::int32 value);

  // optional int32 elementid = 4;
  bool has_elementid() const;
  void clear_elementid();
  static const int kElementidFieldNumber = 4;
  ::google::protobuf::int32 elementid() const;
  void set_elementid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:atd.map.SurElement)
 private:
  void set_has_majortype();
  void clear_has_majortype();
  void set_has_minortype();
  void clear_has_minortype();
  void set_has_elementid();
  void clear_has_elementid();

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::atd::common::Point2D > onepoint_;
  ::google::protobuf::int32 majortype_;
  ::google::protobuf::int32 minortype_;
  ::google::protobuf::int32 elementid_;
  friend struct protobuf_modules_2fipc_2fmessage_2fprotobuf_2fhdmap_2fenginesurmap_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SurElements : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:atd.map.SurElements) */ {
 public:
  SurElements();
  virtual ~SurElements();

  SurElements(const SurElements& from);

  inline SurElements& operator=(const SurElements& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const SurElements& default_instance();

  static inline const SurElements* internal_default_instance() {
    return reinterpret_cast<const SurElements*>(
               &_SurElements_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(SurElements* other);

  // implements Message ----------------------------------------------

  inline SurElements* New() const PROTOBUF_FINAL { return New(NULL); }

  SurElements* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    PROTOBUF_FINAL;
  void CopyFrom(const SurElements& from);
  void MergeFrom(const SurElements& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  void DiscardUnknownFields();
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SurElements* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .atd.map.SurElement oneelement = 2;
  int oneelement_size() const;
  void clear_oneelement();
  static const int kOneelementFieldNumber = 2;
  const ::atd::map::SurElement& oneelement(int index) const;
  ::atd::map::SurElement* mutable_oneelement(int index);
  ::atd::map::SurElement* add_oneelement();
  ::google::protobuf::RepeatedPtrField< ::atd::map::SurElement >*
      mutable_oneelement();
  const ::google::protobuf::RepeatedPtrField< ::atd::map::SurElement >&
      oneelement() const;

  // optional int32 subcode = 1;
  bool has_subcode() const;
  void clear_subcode();
  static const int kSubcodeFieldNumber = 1;
  ::google::protobuf::int32 subcode() const;
  void set_subcode(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:atd.map.SurElements)
 private:
  void set_has_subcode();
  void clear_has_subcode();

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::atd::map::SurElement > oneelement_;
  ::google::protobuf::int32 subcode_;
  friend struct protobuf_modules_2fipc_2fmessage_2fprotobuf_2fhdmap_2fenginesurmap_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class EngineSurMap : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:atd.map.EngineSurMap) */ {
 public:
  EngineSurMap();
  virtual ~EngineSurMap();

  EngineSurMap(const EngineSurMap& from);

  inline EngineSurMap& operator=(const EngineSurMap& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const EngineSurMap& default_instance();

  static inline const EngineSurMap* internal_default_instance() {
    return reinterpret_cast<const EngineSurMap*>(
               &_EngineSurMap_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(EngineSurMap* other);

  // implements Message ----------------------------------------------

  inline EngineSurMap* New() const PROTOBUF_FINAL { return New(NULL); }

  EngineSurMap* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    PROTOBUF_FINAL;
  void CopyFrom(const EngineSurMap& from);
  void MergeFrom(const EngineSurMap& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  void DiscardUnknownFields();
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(EngineSurMap* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .atd.map.SurElements elements = 4;
  int elements_size() const;
  void clear_elements();
  static const int kElementsFieldNumber = 4;
  const ::atd::map::SurElements& elements(int index) const;
  ::atd::map::SurElements* mutable_elements(int index);
  ::atd::map::SurElements* add_elements();
  ::google::protobuf::RepeatedPtrField< ::atd::map::SurElements >*
      mutable_elements();
  const ::google::protobuf::RepeatedPtrField< ::atd::map::SurElements >&
      elements() const;

  // optional .atd.common.Header header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  const ::atd::common::Header& header() const;
  ::atd::common::Header* mutable_header();
  ::atd::common::Header* release_header();
  void set_allocated_header(::atd::common::Header* header);

  // optional .atd.common.Reserved reservedmsg = 2;
  bool has_reservedmsg() const;
  void clear_reservedmsg();
  static const int kReservedmsgFieldNumber = 2;
  const ::atd::common::Reserved& reservedmsg() const;
  ::atd::common::Reserved* mutable_reservedmsg();
  ::atd::common::Reserved* release_reservedmsg();
  void set_allocated_reservedmsg(::atd::common::Reserved* reservedmsg);

  // optional .atd.localization.Pose pose = 3;
  bool has_pose() const;
  void clear_pose();
  static const int kPoseFieldNumber = 3;
  const ::atd::localization::Pose& pose() const;
  ::atd::localization::Pose* mutable_pose();
  ::atd::localization::Pose* release_pose();
  void set_allocated_pose(::atd::localization::Pose* pose);

  // optional .atd.map.ONE_PARKING_SITE oneparkingsite = 5;
  bool has_oneparkingsite() const;
  void clear_oneparkingsite();
  static const int kOneparkingsiteFieldNumber = 5;
  const ::atd::map::ONE_PARKING_SITE& oneparkingsite() const;
  ::atd::map::ONE_PARKING_SITE* mutable_oneparkingsite();
  ::atd::map::ONE_PARKING_SITE* release_oneparkingsite();
  void set_allocated_oneparkingsite(::atd::map::ONE_PARKING_SITE* oneparkingsite);

  // @@protoc_insertion_point(class_scope:atd.map.EngineSurMap)
 private:
  void set_has_header();
  void clear_has_header();
  void set_has_reservedmsg();
  void clear_has_reservedmsg();
  void set_has_pose();
  void clear_has_pose();
  void set_has_oneparkingsite();
  void clear_has_oneparkingsite();

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::atd::map::SurElements > elements_;
  ::atd::common::Header* header_;
  ::atd::common::Reserved* reservedmsg_;
  ::atd::localization::Pose* pose_;
  ::atd::map::ONE_PARKING_SITE* oneparkingsite_;
  friend struct protobuf_modules_2fipc_2fmessage_2fprotobuf_2fhdmap_2fenginesurmap_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// SurElement

// optional int32 majortype = 1;
inline bool SurElement::has_majortype() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SurElement::set_has_majortype() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SurElement::clear_has_majortype() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SurElement::clear_majortype() {
  majortype_ = 0;
  clear_has_majortype();
}
inline ::google::protobuf::int32 SurElement::majortype() const {
  // @@protoc_insertion_point(field_get:atd.map.SurElement.majortype)
  return majortype_;
}
inline void SurElement::set_majortype(::google::protobuf::int32 value) {
  set_has_majortype();
  majortype_ = value;
  // @@protoc_insertion_point(field_set:atd.map.SurElement.majortype)
}

// optional int32 minortype = 2;
inline bool SurElement::has_minortype() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SurElement::set_has_minortype() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SurElement::clear_has_minortype() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SurElement::clear_minortype() {
  minortype_ = 0;
  clear_has_minortype();
}
inline ::google::protobuf::int32 SurElement::minortype() const {
  // @@protoc_insertion_point(field_get:atd.map.SurElement.minortype)
  return minortype_;
}
inline void SurElement::set_minortype(::google::protobuf::int32 value) {
  set_has_minortype();
  minortype_ = value;
  // @@protoc_insertion_point(field_set:atd.map.SurElement.minortype)
}

// repeated .atd.common.Point2D onepoint = 3;
inline int SurElement::onepoint_size() const {
  return onepoint_.size();
}
inline void SurElement::clear_onepoint() {
  onepoint_.Clear();
}
inline const ::atd::common::Point2D& SurElement::onepoint(int index) const {
  // @@protoc_insertion_point(field_get:atd.map.SurElement.onepoint)
  return onepoint_.Get(index);
}
inline ::atd::common::Point2D* SurElement::mutable_onepoint(int index) {
  // @@protoc_insertion_point(field_mutable:atd.map.SurElement.onepoint)
  return onepoint_.Mutable(index);
}
inline ::atd::common::Point2D* SurElement::add_onepoint() {
  // @@protoc_insertion_point(field_add:atd.map.SurElement.onepoint)
  return onepoint_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::atd::common::Point2D >*
SurElement::mutable_onepoint() {
  // @@protoc_insertion_point(field_mutable_list:atd.map.SurElement.onepoint)
  return &onepoint_;
}
inline const ::google::protobuf::RepeatedPtrField< ::atd::common::Point2D >&
SurElement::onepoint() const {
  // @@protoc_insertion_point(field_list:atd.map.SurElement.onepoint)
  return onepoint_;
}

// optional int32 elementid = 4;
inline bool SurElement::has_elementid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void SurElement::set_has_elementid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void SurElement::clear_has_elementid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void SurElement::clear_elementid() {
  elementid_ = 0;
  clear_has_elementid();
}
inline ::google::protobuf::int32 SurElement::elementid() const {
  // @@protoc_insertion_point(field_get:atd.map.SurElement.elementid)
  return elementid_;
}
inline void SurElement::set_elementid(::google::protobuf::int32 value) {
  set_has_elementid();
  elementid_ = value;
  // @@protoc_insertion_point(field_set:atd.map.SurElement.elementid)
}

// -------------------------------------------------------------------

// SurElements

// optional int32 subcode = 1;
inline bool SurElements::has_subcode() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SurElements::set_has_subcode() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SurElements::clear_has_subcode() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SurElements::clear_subcode() {
  subcode_ = 0;
  clear_has_subcode();
}
inline ::google::protobuf::int32 SurElements::subcode() const {
  // @@protoc_insertion_point(field_get:atd.map.SurElements.subcode)
  return subcode_;
}
inline void SurElements::set_subcode(::google::protobuf::int32 value) {
  set_has_subcode();
  subcode_ = value;
  // @@protoc_insertion_point(field_set:atd.map.SurElements.subcode)
}

// repeated .atd.map.SurElement oneelement = 2;
inline int SurElements::oneelement_size() const {
  return oneelement_.size();
}
inline void SurElements::clear_oneelement() {
  oneelement_.Clear();
}
inline const ::atd::map::SurElement& SurElements::oneelement(int index) const {
  // @@protoc_insertion_point(field_get:atd.map.SurElements.oneelement)
  return oneelement_.Get(index);
}
inline ::atd::map::SurElement* SurElements::mutable_oneelement(int index) {
  // @@protoc_insertion_point(field_mutable:atd.map.SurElements.oneelement)
  return oneelement_.Mutable(index);
}
inline ::atd::map::SurElement* SurElements::add_oneelement() {
  // @@protoc_insertion_point(field_add:atd.map.SurElements.oneelement)
  return oneelement_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::atd::map::SurElement >*
SurElements::mutable_oneelement() {
  // @@protoc_insertion_point(field_mutable_list:atd.map.SurElements.oneelement)
  return &oneelement_;
}
inline const ::google::protobuf::RepeatedPtrField< ::atd::map::SurElement >&
SurElements::oneelement() const {
  // @@protoc_insertion_point(field_list:atd.map.SurElements.oneelement)
  return oneelement_;
}

// -------------------------------------------------------------------

// EngineSurMap

// optional .atd.common.Header header = 1;
inline bool EngineSurMap::has_header() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void EngineSurMap::set_has_header() {
  _has_bits_[0] |= 0x00000001u;
}
inline void EngineSurMap::clear_has_header() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void EngineSurMap::clear_header() {
  if (header_ != NULL) header_->::atd::common::Header::Clear();
  clear_has_header();
}
inline const ::atd::common::Header& EngineSurMap::header() const {
  // @@protoc_insertion_point(field_get:atd.map.EngineSurMap.header)
  return header_ != NULL ? *header_
                         : *::atd::common::Header::internal_default_instance();
}
inline ::atd::common::Header* EngineSurMap::mutable_header() {
  set_has_header();
  if (header_ == NULL) {
    header_ = new ::atd::common::Header;
  }
  // @@protoc_insertion_point(field_mutable:atd.map.EngineSurMap.header)
  return header_;
}
inline ::atd::common::Header* EngineSurMap::release_header() {
  // @@protoc_insertion_point(field_release:atd.map.EngineSurMap.header)
  clear_has_header();
  ::atd::common::Header* temp = header_;
  header_ = NULL;
  return temp;
}
inline void EngineSurMap::set_allocated_header(::atd::common::Header* header) {
  delete header_;
  header_ = header;
  if (header) {
    set_has_header();
  } else {
    clear_has_header();
  }
  // @@protoc_insertion_point(field_set_allocated:atd.map.EngineSurMap.header)
}

// optional .atd.common.Reserved reservedmsg = 2;
inline bool EngineSurMap::has_reservedmsg() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void EngineSurMap::set_has_reservedmsg() {
  _has_bits_[0] |= 0x00000002u;
}
inline void EngineSurMap::clear_has_reservedmsg() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void EngineSurMap::clear_reservedmsg() {
  if (reservedmsg_ != NULL) reservedmsg_->::atd::common::Reserved::Clear();
  clear_has_reservedmsg();
}
inline const ::atd::common::Reserved& EngineSurMap::reservedmsg() const {
  // @@protoc_insertion_point(field_get:atd.map.EngineSurMap.reservedmsg)
  return reservedmsg_ != NULL ? *reservedmsg_
                         : *::atd::common::Reserved::internal_default_instance();
}
inline ::atd::common::Reserved* EngineSurMap::mutable_reservedmsg() {
  set_has_reservedmsg();
  if (reservedmsg_ == NULL) {
    reservedmsg_ = new ::atd::common::Reserved;
  }
  // @@protoc_insertion_point(field_mutable:atd.map.EngineSurMap.reservedmsg)
  return reservedmsg_;
}
inline ::atd::common::Reserved* EngineSurMap::release_reservedmsg() {
  // @@protoc_insertion_point(field_release:atd.map.EngineSurMap.reservedmsg)
  clear_has_reservedmsg();
  ::atd::common::Reserved* temp = reservedmsg_;
  reservedmsg_ = NULL;
  return temp;
}
inline void EngineSurMap::set_allocated_reservedmsg(::atd::common::Reserved* reservedmsg) {
  delete reservedmsg_;
  reservedmsg_ = reservedmsg;
  if (reservedmsg) {
    set_has_reservedmsg();
  } else {
    clear_has_reservedmsg();
  }
  // @@protoc_insertion_point(field_set_allocated:atd.map.EngineSurMap.reservedmsg)
}

// optional .atd.localization.Pose pose = 3;
inline bool EngineSurMap::has_pose() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void EngineSurMap::set_has_pose() {
  _has_bits_[0] |= 0x00000004u;
}
inline void EngineSurMap::clear_has_pose() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void EngineSurMap::clear_pose() {
  if (pose_ != NULL) pose_->::atd::localization::Pose::Clear();
  clear_has_pose();
}
inline const ::atd::localization::Pose& EngineSurMap::pose() const {
  // @@protoc_insertion_point(field_get:atd.map.EngineSurMap.pose)
  return pose_ != NULL ? *pose_
                         : *::atd::localization::Pose::internal_default_instance();
}
inline ::atd::localization::Pose* EngineSurMap::mutable_pose() {
  set_has_pose();
  if (pose_ == NULL) {
    pose_ = new ::atd::localization::Pose;
  }
  // @@protoc_insertion_point(field_mutable:atd.map.EngineSurMap.pose)
  return pose_;
}
inline ::atd::localization::Pose* EngineSurMap::release_pose() {
  // @@protoc_insertion_point(field_release:atd.map.EngineSurMap.pose)
  clear_has_pose();
  ::atd::localization::Pose* temp = pose_;
  pose_ = NULL;
  return temp;
}
inline void EngineSurMap::set_allocated_pose(::atd::localization::Pose* pose) {
  delete pose_;
  pose_ = pose;
  if (pose) {
    set_has_pose();
  } else {
    clear_has_pose();
  }
  // @@protoc_insertion_point(field_set_allocated:atd.map.EngineSurMap.pose)
}

// repeated .atd.map.SurElements elements = 4;
inline int EngineSurMap::elements_size() const {
  return elements_.size();
}
inline void EngineSurMap::clear_elements() {
  elements_.Clear();
}
inline const ::atd::map::SurElements& EngineSurMap::elements(int index) const {
  // @@protoc_insertion_point(field_get:atd.map.EngineSurMap.elements)
  return elements_.Get(index);
}
inline ::atd::map::SurElements* EngineSurMap::mutable_elements(int index) {
  // @@protoc_insertion_point(field_mutable:atd.map.EngineSurMap.elements)
  return elements_.Mutable(index);
}
inline ::atd::map::SurElements* EngineSurMap::add_elements() {
  // @@protoc_insertion_point(field_add:atd.map.EngineSurMap.elements)
  return elements_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::atd::map::SurElements >*
EngineSurMap::mutable_elements() {
  // @@protoc_insertion_point(field_mutable_list:atd.map.EngineSurMap.elements)
  return &elements_;
}
inline const ::google::protobuf::RepeatedPtrField< ::atd::map::SurElements >&
EngineSurMap::elements() const {
  // @@protoc_insertion_point(field_list:atd.map.EngineSurMap.elements)
  return elements_;
}

// optional .atd.map.ONE_PARKING_SITE oneparkingsite = 5;
inline bool EngineSurMap::has_oneparkingsite() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void EngineSurMap::set_has_oneparkingsite() {
  _has_bits_[0] |= 0x00000008u;
}
inline void EngineSurMap::clear_has_oneparkingsite() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void EngineSurMap::clear_oneparkingsite() {
  if (oneparkingsite_ != NULL) oneparkingsite_->::atd::map::ONE_PARKING_SITE::Clear();
  clear_has_oneparkingsite();
}
inline const ::atd::map::ONE_PARKING_SITE& EngineSurMap::oneparkingsite() const {
  // @@protoc_insertion_point(field_get:atd.map.EngineSurMap.oneparkingsite)
  return oneparkingsite_ != NULL ? *oneparkingsite_
                         : *::atd::map::ONE_PARKING_SITE::internal_default_instance();
}
inline ::atd::map::ONE_PARKING_SITE* EngineSurMap::mutable_oneparkingsite() {
  set_has_oneparkingsite();
  if (oneparkingsite_ == NULL) {
    oneparkingsite_ = new ::atd::map::ONE_PARKING_SITE;
  }
  // @@protoc_insertion_point(field_mutable:atd.map.EngineSurMap.oneparkingsite)
  return oneparkingsite_;
}
inline ::atd::map::ONE_PARKING_SITE* EngineSurMap::release_oneparkingsite() {
  // @@protoc_insertion_point(field_release:atd.map.EngineSurMap.oneparkingsite)
  clear_has_oneparkingsite();
  ::atd::map::ONE_PARKING_SITE* temp = oneparkingsite_;
  oneparkingsite_ = NULL;
  return temp;
}
inline void EngineSurMap::set_allocated_oneparkingsite(::atd::map::ONE_PARKING_SITE* oneparkingsite) {
  delete oneparkingsite_;
  oneparkingsite_ = oneparkingsite;
  if (oneparkingsite) {
    set_has_oneparkingsite();
  } else {
    clear_has_oneparkingsite();
  }
  // @@protoc_insertion_point(field_set_allocated:atd.map.EngineSurMap.oneparkingsite)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace map
}  // namespace atd

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_modules_2fipc_2fmessage_2fprotobuf_2fhdmap_2fenginesurmap_2eproto__INCLUDED
