#ifndef _PLATOON_PROTOCOLCHANNEL_H_
#define _PLATOON_PROTOCOLCHANNEL_H_

// world model
#define PLATOON_CHANNEL_NAME_WORLDMODEL_OTHER_OBJECTS_INFO "WORLDMODEL_OTHER_OBJECTS_INFO"

// v2x communication
#define PLATOON_CHANNEL_NAME_V2X_OTHER_VEHICLE_INFO "V2X_OTHER_VEHICLE_INFO"

// ego vehicle state
#define PLATOON_CHANNEL_NAME_VCU_VEHICLE_INFO "VCU_VEHICLE_INFO"

#define PLATOON_CHANNEL_NAME_INERTIAL "RAW_INS"

#define PLATOON_CHANNEL_NAME_EGO_VEHICLE_INFO "EGO_VEHICLE_INFO"

#endif // _PLATOON_PROTOCOLCHANNEL_H_
