// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/ipc/message/protobuf/common/reserved.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "modules/ipc/message/protobuf/common/reserved.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)

namespace atd {
namespace common {
class ReservedDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<Reserved> {
} _Reserved_default_instance_;

namespace protobuf_modules_2fipc_2fmessage_2fprotobuf_2fcommon_2freserved_2eproto {

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
};


void TableStruct::Shutdown() {
  _Reserved_default_instance_.Shutdown();
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _Reserved_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
#endif  // GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER

}  // namespace protobuf_modules_2fipc_2fmessage_2fprotobuf_2fcommon_2freserved_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Reserved::kReservedMsgFieldNumber;
const int Reserved::kReservedBitFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Reserved::Reserved()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_modules_2fipc_2fmessage_2fprotobuf_2fcommon_2freserved_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:atd.common.Reserved)
}
Reserved::Reserved(const Reserved& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  reserved_msg_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_reserved_msg()) {
    reserved_msg_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.reserved_msg_);
  }
  reserved_bit_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_reserved_bit()) {
    reserved_bit_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.reserved_bit_);
  }
  // @@protoc_insertion_point(copy_constructor:atd.common.Reserved)
}

void Reserved::SharedCtor() {
  _cached_size_ = 0;
  reserved_msg_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  reserved_bit_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

Reserved::~Reserved() {
  // @@protoc_insertion_point(destructor:atd.common.Reserved)
  SharedDtor();
}

void Reserved::SharedDtor() {
  reserved_msg_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  reserved_bit_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Reserved::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const Reserved& Reserved::default_instance() {
  protobuf_modules_2fipc_2fmessage_2fprotobuf_2fcommon_2freserved_2eproto::InitDefaults();
  return *internal_default_instance();
}

Reserved* Reserved::New(::google::protobuf::Arena* arena) const {
  Reserved* n = new Reserved;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Reserved::Clear() {
// @@protoc_insertion_point(message_clear_start:atd.common.Reserved)
  if (_has_bits_[0 / 32] & 3u) {
    if (has_reserved_msg()) {
      GOOGLE_DCHECK(!reserved_msg_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*reserved_msg_.UnsafeRawStringPointer())->clear();
    }
    if (has_reserved_bit()) {
      GOOGLE_DCHECK(!reserved_bit_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*reserved_bit_.UnsafeRawStringPointer())->clear();
    }
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool Reserved::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::LazyStringOutputStream unknown_fields_string(
      ::google::protobuf::NewPermanentCallback(&_internal_metadata_,
          &::google::protobuf::internal::InternalMetadataWithArenaLite::
              mutable_unknown_fields));
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string, false);
  // @@protoc_insertion_point(parse_start:atd.common.Reserved)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string reserved_msg = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_reserved_msg()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string reserved_bit = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_reserved_bit()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:atd.common.Reserved)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:atd.common.Reserved)
  return false;
#undef DO_
}

void Reserved::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:atd.common.Reserved)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string reserved_msg = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->reserved_msg(), output);
  }

  // optional string reserved_bit = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->reserved_bit(), output);
  }

  output->WriteRaw(unknown_fields().data(),
                   static_cast<int>(unknown_fields().size()));
  // @@protoc_insertion_point(serialize_end:atd.common.Reserved)
}

size_t Reserved::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:atd.common.Reserved)
  size_t total_size = 0;

  total_size += unknown_fields().size();

  if (_has_bits_[0 / 32] & 3u) {
    // optional string reserved_msg = 1;
    if (has_reserved_msg()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->reserved_msg());
    }

    // optional string reserved_bit = 2;
    if (has_reserved_bit()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->reserved_bit());
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Reserved::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const Reserved*>(&from));
}

void Reserved::MergeFrom(const Reserved& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:atd.common.Reserved)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_reserved_msg();
      reserved_msg_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.reserved_msg_);
    }
    if (cached_has_bits & 0x00000002u) {
      set_has_reserved_bit();
      reserved_bit_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.reserved_bit_);
    }
  }
}

void Reserved::CopyFrom(const Reserved& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:atd.common.Reserved)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Reserved::IsInitialized() const {
  return true;
}

void Reserved::Swap(Reserved* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Reserved::InternalSwap(Reserved* other) {
  reserved_msg_.Swap(&other->reserved_msg_);
  reserved_bit_.Swap(&other->reserved_bit_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string Reserved::GetTypeName() const {
  return "atd.common.Reserved";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Reserved

// optional string reserved_msg = 1;
bool Reserved::has_reserved_msg() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void Reserved::set_has_reserved_msg() {
  _has_bits_[0] |= 0x00000001u;
}
void Reserved::clear_has_reserved_msg() {
  _has_bits_[0] &= ~0x00000001u;
}
void Reserved::clear_reserved_msg() {
  reserved_msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_reserved_msg();
}
const ::std::string& Reserved::reserved_msg() const {
  // @@protoc_insertion_point(field_get:atd.common.Reserved.reserved_msg)
  return reserved_msg_.GetNoArena();
}
void Reserved::set_reserved_msg(const ::std::string& value) {
  set_has_reserved_msg();
  reserved_msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:atd.common.Reserved.reserved_msg)
}
#if LANG_CXX11
void Reserved::set_reserved_msg(::std::string&& value) {
  set_has_reserved_msg();
  reserved_msg_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:atd.common.Reserved.reserved_msg)
}
#endif
void Reserved::set_reserved_msg(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_reserved_msg();
  reserved_msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:atd.common.Reserved.reserved_msg)
}
void Reserved::set_reserved_msg(const char* value, size_t size) {
  set_has_reserved_msg();
  reserved_msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:atd.common.Reserved.reserved_msg)
}
::std::string* Reserved::mutable_reserved_msg() {
  set_has_reserved_msg();
  // @@protoc_insertion_point(field_mutable:atd.common.Reserved.reserved_msg)
  return reserved_msg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* Reserved::release_reserved_msg() {
  // @@protoc_insertion_point(field_release:atd.common.Reserved.reserved_msg)
  clear_has_reserved_msg();
  return reserved_msg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void Reserved::set_allocated_reserved_msg(::std::string* reserved_msg) {
  if (reserved_msg != NULL) {
    set_has_reserved_msg();
  } else {
    clear_has_reserved_msg();
  }
  reserved_msg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), reserved_msg);
  // @@protoc_insertion_point(field_set_allocated:atd.common.Reserved.reserved_msg)
}

// optional string reserved_bit = 2;
bool Reserved::has_reserved_bit() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void Reserved::set_has_reserved_bit() {
  _has_bits_[0] |= 0x00000002u;
}
void Reserved::clear_has_reserved_bit() {
  _has_bits_[0] &= ~0x00000002u;
}
void Reserved::clear_reserved_bit() {
  reserved_bit_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_reserved_bit();
}
const ::std::string& Reserved::reserved_bit() const {
  // @@protoc_insertion_point(field_get:atd.common.Reserved.reserved_bit)
  return reserved_bit_.GetNoArena();
}
void Reserved::set_reserved_bit(const ::std::string& value) {
  set_has_reserved_bit();
  reserved_bit_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:atd.common.Reserved.reserved_bit)
}
#if LANG_CXX11
void Reserved::set_reserved_bit(::std::string&& value) {
  set_has_reserved_bit();
  reserved_bit_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:atd.common.Reserved.reserved_bit)
}
#endif
void Reserved::set_reserved_bit(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_reserved_bit();
  reserved_bit_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:atd.common.Reserved.reserved_bit)
}
void Reserved::set_reserved_bit(const char* value, size_t size) {
  set_has_reserved_bit();
  reserved_bit_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:atd.common.Reserved.reserved_bit)
}
::std::string* Reserved::mutable_reserved_bit() {
  set_has_reserved_bit();
  // @@protoc_insertion_point(field_mutable:atd.common.Reserved.reserved_bit)
  return reserved_bit_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* Reserved::release_reserved_bit() {
  // @@protoc_insertion_point(field_release:atd.common.Reserved.reserved_bit)
  clear_has_reserved_bit();
  return reserved_bit_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void Reserved::set_allocated_reserved_bit(::std::string* reserved_bit) {
  if (reserved_bit != NULL) {
    set_has_reserved_bit();
  } else {
    clear_has_reserved_bit();
  }
  reserved_bit_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), reserved_bit);
  // @@protoc_insertion_point(field_set_allocated:atd.common.Reserved.reserved_bit)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace common
}  // namespace atd

// @@protoc_insertion_point(global_scope)
